apiVersion: 1

contactPoints:
  - orgId: 1
    name: Incident Response
    receivers:
      - uid: order-tracker-incident-response
        type: webhook
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST
          maxAlerts: "20"
        disableResolveMessage: false
